# Generated by Django 3.2.11 on 2022-01-21 03:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_photo_gallery.blocks
import wagtail_photo_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BT1PhotoGallery',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(max_length=250)),
                ('content', wagtail.core.fields.StreamField([('gallery', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('collection', wagtail_photo_gallery.blocks.CollectionChooserBlock())]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_photo_gallery.models.ImageGalleryMixin, 'wagtailcore.page'),
        ),
    ]
