# Generated by Django 3.2.11 on 2022-02-20 18:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogw3cssexperimentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogw3cssexperimentpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
